### ISSUE TITLE
Io Error: failed to lookup address information: nodename nor servname provided, or not known

### ISSUE THREAD

**Issue by jlongland** [instructure/canvas-data-loader#3] opened 2017-12-18 23:53 UTC
Encountering some odd behaviour with Canvas Data Loader. CDL runs but files aren't downloaded and no data is loaded into the database. DumpIDs are recorded in rocksdb and it opens a connection to postgres, but with no files downloaded there's nothing to load.

I've never used Rust, but I've managed to trace it to api_client.rs:
```
          let uri = try!(file_to_download.url.parse());
          work_to_do.push(client.get(uri).and_then(move |res| {
            let download_path = cloned_download_path;
            let mut file = File::create(Path::new(&download_path)).expect("Failed to create download file");
            res.body().for_each(move |chunk| {
              let _ = file.write(&*chunk);
              Ok(())
            })
          })
          );
        }
      }
    }
    try!(core.run(join_all(work_to_do)));
```

If I modify core.run to use expect instead of try: `core.run(join_all(work_to_do)).expect("Failed");` an Io Error is thrown.

```
thread 'main' panicked at 'Failed: Io(Error { repr: Custom(Custom { kind: Other, error: StringError("failed to lookup address information: nodename nor servname provided, or not known") }) })', src/libcore/result.rs:906:4
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic
   6: std::panicking::begin_panic_fmt
   7: rust_begin_unwind
   8: core::panicking::panic_fmt
   9: core::result::unwrap_failed
  10: cdl_runner::api_client::CanvasDataApiClient::download_files_for_dump
  11: cdl_runner::main::{{closure}}
  12: cdl_runner::main
  13: __rust_maybe_catch_panic
  14: std::rt::lang_start
```

It seems that I can get CDL working if I download each file individually:

```
          let mut work = client.get(uri).and_then(move |res| {
            let download_path = cloned_download_path;
            let mut file = File::create(Path::new(&download_path)).expect("Failed to create download file");
            res.body().for_each(move |chunk| {
              let _ = file.write(&*chunk);
              Ok(())
            })
          });
          try!(core.run(work));
```

I'm happy to chase this down further, but being new to Rust, I could use some guidance. The lookup failure just seems particularly weird to me.

### Additional Information ###
* Rust Version 1.22.1
* Platform: OSX 10.11.6
* Logs: Trace output is 211,845 lines. Can provide if desired.

**Comment by jlongland** [comment] 2017-12-19 18:26
Thinking this might be an OSX issue. In Console I can see an MDNSResponder error as CDL panics:

2017-12-19 10:00:03.663 AM mDNSResponder[102]:  29: Could not write data to client PID[23218](cdl-runner) because of error - aborting connection
2017-12-19 10:00:03.663 AM mDNSResponder[102]:  29: DNSServiceCreateConnection: 0 registered records, 8 kDNSServiceFlagsShareConnection operations PID[23218](cdl-runner)
2017-12-19 10:00:03.663 AM mDNSResponder[102]:  ->  DNSServiceQueryRecord      0x00015000  0 s3-r-w.ca-central-1.amazonaws.com. (Addr) PID[23218]()
2017-12-19 10:00:03.663 AM mDNSResponder[102]:  ->  DNSServiceQueryRecord      0x00015000  0 s3-r-w.ca-central-1.amazonaws.com. (AAAA) PID[23218]()
2017-12-19 10:00:03.663 AM mDNSResponder[102]:  ->  DNSServiceQueryRecord      0x00015000  0 s3-r-w.ca-central-1.amazonaws.com. (Addr) PID[23218]()
2017-12-19 10:00:03.663 AM mDNSResponder[102]:  ->  DNSServiceQueryRecord      0x00015000  0 s3-r-w.ca-central-1.amazonaws.com. (AAAA) PID[23218]()
2017-12-19 10:00:03.663 AM mDNSResponder[102]:  ->  DNSServiceQueryRecord      0x00015000  0 s3-r-w.ca-central-1.amazonaws.com. (Addr) PID[23218]()
2017-12-19 10:00:03.663 AM mDNSResponder[102]:  ->  DNSServiceQueryRecord      0x00015000  0 s3-r-w.ca-central-1.amazonaws.com. (AAAA) PID[23218]()
2017-12-19 10:00:03.663 AM mDNSResponder[102]:  ->  DNSServiceQueryRecord      0x00015000  0 s3-r-w.ca-central-1.amazonaws.com. (Addr) PID[23218]()
2017-12-19 10:00:03.664 AM mDNSResponder[102]:  ->  DNSServiceQueryRecord      0x00015000  0 s3-r-w.ca-central-1.amazonaws.com. (AAAA) PID[23218]()

**Comment by jlongland** [comment] 2017-12-19 23:41
Added entries to `/etc/hosts/` for:
```
52.95.147.16 s3-r-w.ca-central-1.amazonaws.com
52.95.147.16 hosted-data-work-ca-central-1.s3.ca-central-1.amazonaws.com
```
No longer receiving the error 'failed to lookup address information: nodename nor servname provided, or not known'. This might be an OSX issue with a high number of concurrent lookups, but I haven't been able to find much evidence to support this theory.

I've since encountered issues with open file limits and now broken pipes, but I'll open another issue as needed for those. Will leave this issue open for now.

**Comment by SecurityInsanity** [comment] 2017-12-23 00:23
Hey @jlongland ,

Sorry for the slow response on this (it turns out I wasn't watching the repository 😢 ). We haven't noticed this on any of our Mac provisioned machines. That being said they're all using the same configuration.

It seems like you've digged this down pretty far, and I think your logic is following for the most part. That being said can you upload the full logs (gist probably won't handle it, but maybe something like dropbox?).

That being said besides the logs I wonder if it might be possible to capture a recording with: [RR](http://rr-project.org/), and forward that to me? I'm not seeing any errors on the HTTP Crate we're using (which is what that api_client is doing): [As Seen Here](https://github.com/hyperium/hyper/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+dns).

Thanks for doing so much digging on this, I'm hoping I can take it the rest of the way.

**Comment by jlongland** [comment] 2018-01-02 21:25
Hey @SecurityInsanity - just getting back to the office after holidays. Love the idea of RR, but not sure if it will build on OSX?

To re-cap, I've worked around the DNS lookup weirdness by adding entries to /etc/hosts. The problem I was encountering prior to the holidays was that CDL would download ~200 files and then drop I/O sources, panicking because of a broken pipe:

```
TRACE:hyper::client::pool: clean_parked "https://hosted-data-work-ca-central-1.s3.ca-central-1.amazonaws.com"
DEBUG:tokio_core::reactor: dropping I/O source: 4805
TRACE:hyper::client::pool: clean_parked "https://hosted-data-work-ca-central-1.s3.ca-central-1.amazonaws.com"
DEBUG:tokio_core::reactor: dropping I/O source: 4806
TRACE:hyper::client::pool: clean_parked "https://hosted-data-work-ca-central-1.s3.ca-central-1.amazonaws.com"
DEBUG:tokio_core::reactor: dropping I/O source: 4807
TRACE:hyper::client::pool: clean_parked "https://hosted-data-work-ca-central-1.s3.ca-central-1.amazonaws.com"
DEBUG:tokio_core::reactor: dropping I/O source: 4808
TRACE:hyper::client::pool: clean_parked "https://hosted-data-work-ca-central-1.s3.ca-central-1.amazonaws.com"
DEBUG:tokio_core::reactor: dropping I/O source: 4809
thread 'main' panicked at 'Result Error: Error(Hypererror(Io(Error { repr: Custom(Custom { kind: BrokenPipe, error: StringError("broken pipe") }) })), State { next_error: None, backtrace: Some(stack backtrace:
   0:        0x10767b73e - backtrace::backtrace::trace::h4e7695042f07d5c8
   1:        0x10767b77c - backtrace::capture::Backtrace::new::haa2d21b0dc989639
   2:        0x10736cc97 - error_chain::make_backtrace::h7b4f9c7a59cbd8ea
   3:        0x10736cd58 - _$LT$error_chain..State$u20$as$u20$core..default..Default$GT$::default::hf657a8a1b4b18133
   4:        0x10731293d - cdl_runner::api_client::CanvasDataApiClient::download_files_for_dump::h8a06c3b90c3178af
   5:        0x107330fab - cdl_runner::main::_$u7b$$u7b$closure$u7d$$u7d$::h2f498d2c87978d39
   6:        0x10732a020 - cdl_runner::main::ha6ec6f26631e9ae1
   7:        0x10777ae2c - __rust_maybe_catch_panic
   8:        0x1077744f8 - std::rt::lang_start::he59b9a54055aa131) })', src/importer.rs:194:18
```

I couldn't figure out where I was encountering the broken pipe, so I started to look into issues with the Hyper HTTP crate as well as tokio-core. As you mentioned, there aren't any active issues with the Hyper HTTP crate and I didn't come across anything directly relevant in tokio-core. Though it looks like someone [opened a related issue](https://github.com/hyperium/hyper/issues/1403) over the holidays.

I was going to ask how many files you're testing with because the number of files seems to be part of the problem - possibly a pool leak or timeout of some sort? But it doesn't seem to matter now - because CDL is suddenly working. Prior to Dec 30th, our dumps contained thousands of files. For example, the Dec 29th dump has 26 account_dim files - but the Dec 30th dump has 1 account_dim file. With the consolidated files, CDL is able to run to completion. Did anything change with Canvas Data on the 30th?

**Comment by SecurityInsanity** [comment] 2018-01-02 21:54
Hey @jlongland ,

Yea it appears rr doesn't seem to compile on mac os x 😢 I got a bit too excited there. It also looks like the native gdb record which although a bit more primitive doesn't work on os x, and lldb doesn't provide a remote debug method. Which is unfortunate.

We download files on our macs from a variety of schools ranging from a couple hundred files to a couple thousand. That being said I wonder if a differing limit somewhere is causing this issue to show up:

```
$ launchctl limit
    cpu         unlimited      unlimited
    filesize    unlimited      unlimited
    data        unlimited      unlimited
    stack       8388608        67104768
    core        0              unlimited
    rss         unlimited      unlimited
    memlock     unlimited      unlimited
    maxproc     709            1064
    maxfiles    256            unlimited
```

Was run from one of the macs we test with, I'm curious what your limits look like? Unfortunately the "broken pipe" error could mean a couple things so I'm hesitant to jump on a particular train of thinking though without testing.

I'm glad to hear it's working now, but hopefully we can find a root cause to this as I'm sure it may rear it's ugly head for someone again. On the 30th we deployed quite a few updates to Spark which is what we use internally to generate parts of the files, so this is why you're seeing less files.

**Comment by jlongland** [comment] 2018-01-02 22:19
Good to know re: changes on the 30th. It did seem a bit odd to have so many small files, so the consolidated files make more sense.

While chasing this down, I bumped maxproc and maxfiles because I noticed I was hitting the limit:

```
	cpu         unlimited      unlimited
	filesize    unlimited      unlimited
	data        unlimited      unlimited
	stack       8388608        67104768
	core        0              unlimited
	rss         unlimited      unlimited
	memlock     unlimited      unlimited
	maxproc     2048           2048
	maxfiles    65536          65536
```

I'm new to Rust and it's been a long time since I've worked in a low-level language, but my gut feeling is that I was running into something with futures and the hyper/tokio crates. When I changed the api_client to download individually, I was able to download all files:

```
          let mut work = client.get(uri).and_then(move |res| {
            let download_path = cloned_download_path;
            let mut file = File::create(Path::new(&download_path)).expect("Failed to create download file");
            res.body().for_each(move |chunk| {
              let _ = file.write(&*chunk);
              Ok(())
            })
          });
          try!(core.run(work));
```

There were never any errors about being unable to create a file locally, so I'd be inclined to look at the get or the future response. I'd have to learn more about futures, hyper and tokio to pursue it further but I'm happy to be a guinea pig and help you chase this down if you have thoughts on next steps.

**Comment by SecurityInsanity** [comment] 2018-01-02 22:45
Thanks for that @jlongland  can you let me know what the name of your institution, and perhaps send over that log file? I'm hoping that with limits set the same we can get it to reproduce on some older versions of the dumps (or recreate the state).

It's weird that when you run each individual work separately things start to work. I wonder if the real root cause is coming out of: https://github.com/instructure/canvas-data-loader/blob/master/src/api_client.rs#L302 Where we choose to use 4 DNS Working Threads. I wonder if lowering that would also create a "fix" for this issue?

**Comment by SecurityInsanity** [comment] 2018-01-07 07:29
Hey @jlongland,

After digging into this a bit more I was able to replicate this issue on my host :party:. The problem is a bit hard to explain so I won't go to deep into detail as to hopefully not confuse everyone reading this.

The problem is essentially coming out of the fact that we're doing a lot of concurrent DNS lookups on our sockets. (Proving my theory to be correct that is spinning up 4 worker threads was too much for the time being). This is also why when you switched to downloading one at a time you saw it working.

The concurrent lookups speed was the root cause. From researching around this problem can also appear in docker, and an example go binary. So I'm thinking it'll be fine to not file an issue on Hyper/Tokio.

However since our update to spark, and us pushing out larger files should largely negate this OS X issue (by causing the concurrent lookup count to be less, and over a slightly longer period of time). I think it's safe to close this now. That being said if this problem probs up again for anyone, I think we should at that point investigate making the number of DNS resolving threads configurable.

Does this jive with you? Or have you started seeing this issue pop up more recently?

Thanks for taking the time to not only file this issue, but stick with me as I tried reproducing it!

**Comment by SecurityInsanity** [comment] 2018-01-09 22:14
I'm going to assume this jives with no response. If it doesn't please reopen (or if you notice again! please reopen). Thanks for all the detail on this, and waiting for me to work through it.

**Closed by SecurityInsanity** 2018-01-09 22:14 UTC

**Comment by jlongland** [comment] 2018-03-07 20:40
Realized I never followed up on this one - thanks for chasing this down Eric!

**Comment by Jason5Lee** [comment] 2021-04-03 08:08
I met the same problem when I used a tool I wrote that uses tokio's dns resolution. Could you tell me how should I fix it?

**Comment by Mythra** [comment] 2021-04-03 14:53
@Jason5Lee Hey! Unfortunately, the error message is rather generic and could mean a lot of things. This repo is unmaintained right now, but as the former maintainer...

This issue filed I wouldn't use as any sort of indication as to what's wrong with your app, because:

  1. This issue was filed back when Rust, and Tokio were significantly different. Both have gone through massive overhauls (sometimes multiple!) since then.
  2. Since this error message is generic, it really depends on what your application, or libraries interacting with connections is doing. The cases we may throw this error are not going to be the same as yours.
   3. Even if it were the same issue by whatever chance, there is no guarantee that the solution we provided for older OSX versions is still the correct way to solve the issue.

I'm sorry to be the bearer of bad news, and I hope you're able to find the culprit to your issue!

**Comment by Jason5Lee** [comment] 2021-04-03 15:18
Thanks for the reply. I think I found a way to minimalize it.
